const main = document.querySelector('#main');
const state = {q:'', category:'', sort:'popular', page:1, buyTogether:false, metrics:null, categories:[], cart:[], request:0, savedMode:'demo'};
try { state.cart = JSON.parse(localStorage.getItem('ocean-cart') || '[]').filter(p=>p&&/^\d{10}$/.test(p.article_id)).slice(0,30); state.savedMode=localStorage.getItem('ocean-cart-mode')||'demo'; } catch { state.cart=[]; }
const esc = s => String(s ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = n => Number(n || 0).toLocaleString('vi-VN');
const labels = {'Garment Upper body':'Áo & áo khoác','Garment Lower body':'Quần & chân váy','Garment Full body':'Váy & đầm','Accessories':'Phụ kiện','Shoes':'Giày dép','Underwear':'Đồ mặc trong','Socks & Tights':'Tất'};
const categoryLabel = c => labels[c] || c;
const price = p => p.demo_price_vnd ? `${number(p.demo_price_vnd)} ₫` : '';
async function api(path) {const r=await fetch(path);const d=await r.json();if(!r.ok)throw Error(d.error || 'Không tải được dữ liệu');return d;}
function image(p, cls='') {return `<img class="${cls}" src="${esc(p.image_url)}" alt="${esc(p.name)}" loading="lazy">`;}
function imageFallbacks(){main.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{const fallback=document.createElement('span');fallback.className='photo-fallback';fallback.textContent='Chưa có ảnh sản phẩm';img.replaceWith(fallback);},{once:true}));}
function card(p,rule){return `<a class="product" href="#product/${esc(p.article_id)}"><div class="product-photo">${image(p)}<span class="product-tag">${rule?'Mua kèm':esc(categoryLabel(p.category))}</span></div><div class="product-body"><small>${esc(p.colour || 'OCEAN collection')}</small><h3>${esc(p.name)}</h3>${p.has_buy_together&&!rule?'<small class="recommend-flag">Có gợi ý mua kèm</small>':''}<div class="product-bottom">${price(p)?`<span class="price">${esc(price(p))}</span>`:''}<small>${number(p.purchase_count)} lượt mua${state.metrics?.mode==='demo'?' mẫu':''}</small></div></div></a>`;}
function popularSection(rec){return rec.suggestions?.length?`<section class="panel"><h2>Có thể bạn thích</h2><div class="grid">${rec.suggestions.map(r=>card(r.product)).join('')}</div></section>`:'';}
function qualityRows(m){if(!m.evaluation)return '';const e=m.evaluation;return `<tr><th>Phương pháp đánh giá</th><td>${esc(e.protocol)} · seed ${esc(e.seed??'—')}</td></tr><tr><th>Đơn vị khai phá và đánh giá</th><td>${m.item_level==='product_code'?'Mẫu sản phẩm (gộp các biến thể màu); web hiển thị SKU cụ thể. Các chỉ số test tính ở cấp mẫu.':'SKU cụ thể; các chỉ số test tính ở cấp SKU.'}</td></tr>${[['Sản phẩm phổ biến',e.popularity],['Luật + dự phòng khi thiếu luật',e.hybrid]].filter(([,v])=>v).map(([n,v])=>`<tr><th>${n}</th><td>Precision@6: ${Number(v.precision_at_6).toFixed(4)} · Recall@6: ${Number(v.recall_at_6).toFixed(4)} · Coverage: ${Number(v.coverage).toFixed(4)}</td></tr>`).join('')}`;}
function validationPanel(m){const v=m.validation;if(!v)return '';return `<section class="panel"><h2>Chọn cấu hình trên tập validation</h2><p>Huấn luyện đến ${esc(m.cutoff)}; validation đến ${esc(v.end)}; kiểm tra cuối sau ${esc(v.end)}. Cấu hình chọn theo Recall@6 của FP-Growth trên validation, không dùng tập kiểm tra.</p><div class="table-scroll"><table><thead><tr><th>Support</th><th>Confidence</th><th>Luật</th><th>Recall@6</th><th>Coverage</th></tr></thead><tbody>${v.results.map(r=>`<tr><td>${r.min_support}</td><td>${r.min_confidence}</td><td>${number(r.rules)}</td><td>${Number(r.validation.recall_at_6).toFixed(4)}</td><td>${Number(r.validation.coverage).toFixed(4)}</td></tr>`).join('')}</tbody></table></div></section>`;}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('visible'),2400);}
function saveCart(){try{localStorage.setItem('ocean-cart',JSON.stringify(state.cart));if(state.metrics)localStorage.setItem('ocean-cart-mode',state.metrics.mode);}catch{}document.querySelector('#cart-count').textContent=state.cart.length;}
function setDataMode(m){if(state.savedMode!==m.mode){state.cart=[];state.savedMode=m.mode;}saveCart();}
function addToCart(p){if(state.cart.some(x=>x.article_id===p.article_id))return toast('Sản phẩm đã có trong giỏ');if(state.cart.length>=30)return toast('Giỏ tối đa 30 sản phẩm khác nhau');state.cart.push(p);saveCart();toast('Đã thêm vào giỏ hàng');}
function fail(error){main.innerHTML=`<div class="error"><h2>Chưa tải được dữ liệu</h2><p>${esc(error.message)}</p><button class="primary" id="retry">Thử lại</button></div>`;document.querySelector('#retry').onclick=route;}
async function shop(token){const params=new URLSearchParams({q:state.q,category:state.category,sort:state.sort,page:state.page,buy_together:state.buyTogether?1:0});const data=await api('/api/products?'+params);if(token!==state.request)return;
 main.innerHTML=`${!state.q&&!state.category&&state.page===1?`<section class="hero"><div class="hero-copy"><span class="eyebrow">The everyday edit / 01</span><h1>Mặc theo cách<br>của riêng bạn.</h1><p>Những món đồ dễ mặc, dễ kết hợp.<br>Tìm một món yêu thích, khám phá những món đi cùng.</p><button class="primary" id="discover">Khám phá bộ sưu tập ↗</button></div><div class="hero-art"><img src="/assets/demo-shirt.svg" alt="Minh họa áo sơ mi xanh"><img src="/assets/demo-bag.svg" alt="Minh họa túi đeo"><span class="hero-number">OCEAN / EVERYDAY</span></div></section><section class="benefits"><div><i>↗</i><span><strong>Khám phá phong cách</strong><small>Trang phục & phụ kiện trong một nơi</small></span></div><div><i>⊕</i><span><strong>Tìm món đồ đi cùng</strong><small>Gợi ý ngay tại trang sản phẩm</small></span></div><div><i>♡</i><span><strong>Tạo tủ đồ của bạn</strong><small>Lưu lựa chọn vào giỏ trên thiết bị</small></span></div></section>`:''}<section id="catalog"><div class="section-head"><div><span class="eyebrow">Khám phá OCEAN</span><h2>${state.q?`Kết quả cho “${esc(state.q)}”`:state.category?esc(categoryLabel(state.category)):state.buyTogether?'Sản phẩm có gợi ý mua kèm':'Một chút mới cho tủ đồ'}</h2><p>${number(data.total)} sản phẩm${data.mode==='demo'?' minh họa':''}</p></div><select id="sort" aria-label="Sắp xếp sản phẩm"><option value="popular" ${state.sort==='popular'?'selected':''}>Mua nhiều nhất</option><option value="name" ${state.sort==='name'?'selected':''}>Tên A → Z</option></select></div><div class="chips"><button id="with-rules" class="chip ${state.buyTogether?'active':''}" aria-pressed="${state.buyTogether}">Có gợi ý mua kèm</button><button class="chip ${!state.category?'active':''}" data-filter="">Tất cả</button>${state.categories.map(c=>`<button class="chip ${state.category===c?'active':''}" data-filter="${esc(c)}">${esc(categoryLabel(c))}</button>`).join('')}</div>${data.items.length?`<div class="grid">${data.items.map(p=>card(p)).join('')}</div>`:'<div class="empty">Không tìm thấy sản phẩm. Thử từ khóa hoặc danh mục khác.</div>'}<div class="pager"><button id="prev" ${state.page===1?'disabled':''}>← Trước</button><span>${state.page} / ${Math.max(1,Math.ceil(data.total/data.page_size))}</span><button id="next" ${state.page*data.page_size>=data.total?'disabled':''}>Sau →</button></div></section>`;
 document.querySelector('#discover')?.addEventListener('click',()=>document.querySelector('#catalog').scrollIntoView({behavior:'smooth'}));
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.category=b.dataset.filter;state.page=1;route();});
 document.querySelector('#with-rules').onclick=()=>{state.buyTogether=!state.buyTogether;state.page=1;route();};
 document.querySelector('#sort').onchange=e=>{state.sort=e.target.value;state.page=1;route();};
 document.querySelector('#prev').onclick=()=>{state.page--;route();};document.querySelector('#next').onclick=()=>{state.page++;route();};imageFallbacks();
}
async function detail(id,token){const p=await api('/api/products/'+encodeURIComponent(id));if(token!==state.request)return;
 main.innerHTML=`<div class="breadcrumb"><a href="#shop">Khám phá</a> / ${esc(categoryLabel(p.category))} / ${esc(p.name)}</div><section class="detail"><div class="detail-image">${image(p)}</div><div class="detail-copy"><span class="eyebrow">${esc(categoryLabel(p.category))}</span><h1>${esc(p.name)}</h1><p>${number(p.purchase_count)} lượt mua${state.metrics.mode==='demo'?' trong dữ liệu minh họa':''}</p>${price(p)?`<span class="price">${esc(price(p))}</span>`:''}<p>${esc(p.description || 'Chưa có mô tả sản phẩm.')}</p><dl class="detail-specs"><dt>Mã sản phẩm</dt><dd>${esc(p.article_id)}</dd><dt>Loại sản phẩm</dt><dd>${esc(p.product_type)}</dd><dt>Màu sắc</dt><dd>${esc(p.colour || 'Chưa có dữ liệu')}</dd><dt>Nhóm sản phẩm</dt><dd>${esc(categoryLabel(p.category))}</dd></dl><div class="detail-actions"><button class="primary" id="add-cart">Thêm vào giỏ hàng</button><button class="secondary" id="see-together">Xem món mua kèm ↓</button></div></div></section><section id="together"><div class="section-head"><div><span class="eyebrow">Better together</span><h2>Khách hàng cũng thường mua</h2><p>Những sản phẩm được mua cùng món đồ bạn đang xem.</p></div></div><div id="recommend-content" class="loading">Đang tìm sản phẩm mua kèm…</div></section>`;
 document.querySelector('#add-cart').onclick=()=>addToCart(p);document.querySelector('#see-together').onclick=()=>document.querySelector('#together').scrollIntoView({behavior:'smooth'});imageFallbacks();
 try{const rec=await api('/api/recommendations?items='+id);if(token!==state.request)return;document.querySelector('#recommend-content').className='';document.querySelector('#recommend-content').innerHTML=rec.items.length?`<div class="grid">${rec.items.map(r=>card(r.product,r.rule)).join('')}</div>`:'<div class="empty">Chưa có sản phẩm mua kèm. <a href="#shop">Khám phá sản phẩm khác ↗</a></div>';document.querySelector('#recommend-content').insertAdjacentHTML('beforeend',popularSection(rec));imageFallbacks();}catch(e){if(token===state.request)document.querySelector('#recommend-content').innerHTML=`<div class="error">${esc(e.message)}</div>`;}
}
async function insights(token){const m=await api('/api/metrics');if(token!==state.request)return;state.metrics=m;
 main.innerHTML=`<div class="breadcrumb"><a href="#shop">Khám phá</a> / Góc dữ liệu</div><div class="section-head"><div><span class="eyebrow">Shopping insights</span><h2>Từ hành vi mua sắm đến gợi ý</h2><p>${m.mode==='demo'?'Số liệu minh họa cho giao diện; chưa phải kết quả chạy Kaggle.':`Kết quả mô hình ${esc(m.run_id)} · ${esc(m.trained_at)}`}</p></div></div><div class="stats">${[['Giao dịch sạch',m.transactions],['Giỏ hàng huấn luyện',m.baskets],['Sản phẩm',m.products],['Luật mua kèm',m.rules]].map(([label,value])=>`<div class="stat"><small>${label}</small><strong>${number(value)}</strong></div>`).join('')}</div><section class="panel"><h2>Pipeline của dự án</h2><div class="steps"><div><strong>01 / MongoDB</strong><p>Lưu sản phẩm, khách hàng và giao dịch gốc theo từng đợt nhập.</p></div><div><strong>02 / Apache Spark</strong><p>Làm sạch, giữ mã sản phẩm 10 chữ số, tạo giỏ theo khách hàng + ngày + kênh.</p></div><div><strong>03 / FP-Growth</strong><p>Tìm tập phổ biến và luật kết hợp, đo support, confidence và lift.</p></div><div><strong>04 / Gợi ý mua kèm</strong><p>Áp dụng đủ điều kiện của luật; loại sản phẩm đã chọn và gợi ý trùng.</p></div></div><div class="notice">Dataset không có mã hóa đơn. Giỏ hàng là quy ước phân tích, có thể gộp nhiều lần mua trong cùng ngày và cùng kênh. Đây là gợi ý mua kèm theo sản phẩm, chưa phải cá nhân hóa theo khách hàng.</div></section><section class="panel"><h2>Thông số & chất lượng</h2><div class="table-scroll"><table><tbody><tr><th>minSupport</th><td>${esc(m.parameters.min_support)}</td></tr><tr><th>minConfidence</th><td>${esc(m.parameters.min_confidence)}</td></tr><tr><th>Điều kiện lift</th><td>&gt; ${esc(m.parameters.min_lift)}</td></tr><tr><th>Sản phẩm có luật mua kèm khi xem riêng</th><td>${number(m.recommendable_products)} / ${number(m.products)} · ${Number(100*(m.catalog_rule_coverage||0)).toFixed(2)}% danh mục</td></tr><tr><th>Tập phổ biến</th><td>${number(m.itemsets)}</td></tr><tr><th>Khoảng ngày huấn luyện</th><td>${esc(m.date_range || 'Chưa có dữ liệu thật')}</td></tr><tr><th>Đánh giá theo thời gian</th><td>${m.evaluation?`Precision@6: ${Number(m.evaluation.precision_at_6).toFixed(4)} · Recall@6: ${Number(m.evaluation.recall_at_6).toFixed(4)} · Coverage: ${Number(m.evaluation.coverage).toFixed(4)} (${number(m.evaluation.baskets)} giỏ kiểm tra)`:'Chưa đánh giá; chạy pipeline với --cutoff để giữ lại dữ liệu tương lai.'}</td></tr>${qualityRows(m)}</tbody></table></div></section>${validationPanel(m)}<section class="panel"><h2>Nhóm sản phẩm được mua nhiều</h2><div class="table-scroll"><table><thead><tr><th>Nhóm sản phẩm</th><th>Lượt mua</th><th>Phân bố</th></tr></thead><tbody>${(m.top_categories||[]).map(c=>`<tr><td>${esc(categoryLabel(c.category))}</td><td>${number(c.count)}</td><td><div class="bar"><span style="width:${Math.max(1,Math.min(100,100*c.count/Math.max(...m.top_categories.map(x=>x.count))))}%"></span></div></td></tr>`).join('')}</tbody></table></div></section>`;
}
async function route(){const token=++state.request;main.innerHTML='<div class="loading">Đang tải…</div>';try{if(!state.metrics){const [m,c]=await Promise.all([api('/api/metrics'),api('/api/categories')]);state.metrics=m;state.categories=c.items;setDataMode(m);}if(token!==state.request)return;const hash=location.hash||'#shop';document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===(hash==='#insights'?'#insights':'#shop')));if(hash.startsWith('#product/'))await detail(hash.slice(9),token);else if(hash==='#insights')await insights(token);else await shop(token);}catch(e){if(token===state.request)fail(e);}}
async function renderCart(){const content=document.querySelector('#cart-content');content.innerHTML=state.cart.length?state.cart.map(p=>`<div class="cart-row">${image(p)}<div><strong>${esc(p.name)}</strong>${price(p)?`<small>${esc(price(p))}</small>`:''}</div><button data-remove="${esc(p.article_id)}" aria-label="Xóa ${esc(p.name)}">Xóa</button></div>`).join('')+'<h3>Gợi ý cho cả giỏ hàng</h3><div id="cart-rec">Đang tìm món đi cùng…</div>':'<div class="empty">Giỏ đang trống. Chọn sản phẩm bạn thích và thêm vào giỏ.</div>';
 content.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.cart=state.cart.filter(p=>p.article_id!==b.dataset.remove);saveCart();renderCart();});if(state.cart.length){const ids=state.cart.map(p=>p.article_id).join(',');try{const rec=await api('/api/recommendations?items='+ids);if(ids!==state.cart.map(p=>p.article_id).join(','))return;const box=document.querySelector('#cart-rec');if(box)box.innerHTML=rec.items.length?rec.items.map(r=>`<p><a href="#product/${r.product.article_id}" data-close-cart>${esc(r.product.name)} ↗</a></p>`).join(''):'Chưa có sản phẩm mua kèm cho giỏ hàng.';if(box&&rec.suggestions?.length)box.insertAdjacentHTML('beforeend',`<h3>Có thể bạn thích</h3>${rec.suggestions.map(r=>`<p><a href="#product/${esc(r.product.article_id)}" data-close-cart>${esc(r.product.name)} ↗</a></p>`).join('')}`);content.querySelectorAll('[data-close-cart]').forEach(a=>a.onclick=()=>document.querySelector('#cart-dialog').close());}catch(e){const box=document.querySelector('#cart-rec');if(box)box.textContent=e.message;}}}
document.querySelector('#search-form').onsubmit=e=>{e.preventDefault();state.q=document.querySelector('#search').value.trim();state.page=1;if(location.hash==='#shop')route();else location.hash='shop';};
document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{state.q='';document.querySelector('#search').value='';state.category=state.categories.includes(b.dataset.category)?b.dataset.category:'';state.page=1;if(location.hash==='#shop')route();else location.hash='shop';});
document.querySelector('.brand').onclick=()=>{state.q='';state.category='';state.buyTogether=false;state.page=1;document.querySelector('#search').value='';if(location.hash==='#shop')route();};
document.querySelector('#cart-open').onclick=()=>{renderCart();document.querySelector('#cart-dialog').showModal();};document.querySelector('#cart-close').onclick=()=>document.querySelector('#cart-dialog').close();
window.addEventListener('hashchange',()=>{window.scrollTo(0,0);route();});saveCart();route();

